#ifndef DESK_APP_H
#define DESK_APP_H

#include "desk_types.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct
{
    bool button_up;
    bool button_down;
    bool limit_upper;
    bool limit_lower;
    bool fault_in;       // external fault input (e.g., motor controller)
    uint16_t motor_current_ma;
    uint32_t timestamp_ms;
} AppInput_t;

/**
 * @struct AppOutput_t
 * @brief Application layer outputs (command signals)
 * 
 * Contains all control signals generated by application logic:
 * - Motor control: direction and speed
 * - Status LEDs: 3 independent indicators for visual feedback
 * - Fault indication: latched error state
 * 
 * @field motor_cmd - Commanded motor direction (STOP, UP, DOWN)
 * @field motor_speed - Commanded motor speed (0-255 PWM)
 * @field led_bt_up - UP button LED state (ON when UP button pressed)
 * @field led_bt_down - DOWN button LED state (ON when DOWN button pressed)
 * @field led_error - ERROR LED state (ON when system in fault state)
 * @field fault_out - Latched fault condition flag
 */
typedef struct
{
    MotorDirection_t motor_cmd;      ///< Motor direction command
    uint8_t motor_speed;              ///< Motor speed (PWM 0-255)
    LEDState_t led_bt_up;             ///< UP button indicator LED
    LEDState_t led_bt_down;           ///< DOWN button indicator LED
    LEDState_t led_error;             ///< ERROR state indicator LED
    bool fault_out;                   ///< Latched fault state
} AppOutput_t;

typedef enum
{
    APP_STATE_IDLE = 0,
    APP_STATE_MOVING_UP = 1,
    APP_STATE_MOVING_DOWN = 2,
    APP_STATE_FAULT = 3
} AppState_t;

void APP_Init(void);
void APP_Task(const AppInput_t *inputs, AppOutput_t *outputs);
AppState_t APP_GetState(void);

#ifdef __cplusplus
}
#endif

#endif // DESK_APP_H
